meta-qti-bsp: fix build error for weston and video
Since compiler update, to avoid compilation failure reporting as
"error: do_patch:Missing Upstream-Status in patch".So add
Upstream-Status to fix the compilation error problem

Change-Id: Ie1d022ca692ae32dbbdfb63c31fac34913399170