gst-codec2: fix HY11 issue for kernel 5.15
1. Need to add dependency videodlkm explicitly, which provided common
video headers in kernel 5.15.
2. Refine useless setting.

Error:
codec2wrapper.h:108:10: fatal error: 'media/msm_media_info.h' file not
found

Change-Id: I537185a0bc40860f351402a7e6a0bff7bafd7328
Signed-off-by: Miaomiao Chen <quic_miaochen@quicinc.com>