README: Add maintenance info
Fix test_readme error detected in yocto-check-layer:
AssertionError: 'maintainer' not found in meta-qti-base

Change-Id: Icaf58436787c03c55e76f8f2cf8be379fcfcd28a
Signed-off-by: Zhu Yuqing <quic_zyuqing@quicinc.com>
(cherry picked from commit 7e101a7e22ff67d941c11b082cb0c09441f6e70e)