system-core: Set the properties of build.prop
Error: leprop-service[pid]: Persist File doesnt exist

Root cause:
ll.c FILE *fp = fopen(PROP_FILE_PERSIST_PATH, "w");

Set build.prop to belong to leprop user/group so that leprop.service can access it.

Change-Id: I53842168fd8484e6a8a0f5f546bb6f3ec41d4f8d
Signed-off-by: pengy <quic_pengy@quicinc.com>