meta-qti-bsp : Add SRC_FORMAT for libsquashfs-utils
Change-Id: I8d09a6f91683f9c1aaa62dbad72b68f71b233d0e
FetchError: Fetcher failure: The SRCREV_FORMAT variable must be set when multiple SCMs are used.
(cherry picked from commit dd6f3080f0091d68b420654fd4eea5205c3749c1)