e2fsprogs: resolve configure stage issue
Use UNKNOWN_CONFIGURE_OPT_IGNORE to bypass the error caused by unknown options
configure: WARNING: unrecognized options: --disable-silent-rules, --disable-dependency-tracking, --with-libtool-sysroot, --enable-largefile
ERROR: QA Issue: e2fsprogs: configure was passed unrecognised options: --enable-largefile [unknown-configure-option]

Change-Id: Ia50e71f3c9c0e93a3e814faa10510e109fd9f219