module-sign.bbclass: execute do_module_signing task before do_package_qa
do_module_signing task generates intermediate files "xxx.ko.~signed~" in
packages-split directory, and do_package_qa task will check the files in
this directory. Ensure execute do_module_signing task before do_package_qa
to fix the following random error:

    Exception: FileNotFoundError: [Errno 2] No such file or directory: '../packages-split/qcacld32-ll-hasting-cnss0/lib/modules/5.15.78-perf/extra/qca6696.ko.~signed~'
    Summary: 1 task failed:
	meta-qti-bsp/meta-qti-base/recipes-wlan/wlan/qcacld32-ll-hasting-cnss0_git.bb:do_package_qa

Change-Id: Ief6f1053db00f157bf9f06eb8d89420e023ef763
Signed-off-by: xb <quic_xubaoj@quicinc.com>
(cherry picked from commit 2bd63dfa93a1217791c5888a2c49d346c5395b85)