qti-cpe-image: Update boot_size in misc_info.txt to match partition layout
The boot_size in misc_info.txt (0x011DC000 ~17.8MB) was out of
sync with the actual boot partition size defined in partition.xml
(81920KB ~80MB), causing OTA generation to fail with:

ERROR: boot size (58349568) is 311.58% of limit (18726912)

Update boot_size and recovery_size to 0x05000000 (~80MB) to
match the partition.xml definition.

Fixes: qti-recovery-image OTA generation failure
Change-Id: I66a71618f3bcf1541f8ad292e1a735d5e80d9e12
Signed-off-by: Radhika Bandichhode <rbandich@qti.qualcomm.com>