meta-qti-bsp: update DEPENDS for drm-player-example/gst-drmdecryptor
Add DEPENDS += libutils for drm-player-example/gst-drmdecryptor
to fix the HY11 build error:
DrmAPI.h:20:10: fatal error: utils/List.h: No such file or directory

Change-Id: I1b70e559bac707c552961efdfa11baf949a89cc4
Signed-off-by: Shiming Dong <quic_shimdong@quicinc.com>
(cherry picked from commit ea6405f9a2921463cd63b01a2ff9e4c207764a35)