gst-plugin-codec2: add binder depend to fix hy11 build error
gst-plugin-codec2 depends on codec2-service that depends on binder,
in normal (non-hy11) build, it's okay that gst-plugin-codec2 build
sysroot populated the binder headers.
However, in hy11 build, codec2-service releases binary only and not
built again to populate binder headers, then no binder headers in
gst-plugin-codec2 build sysroot to include.

Fix hy11 build error below:
gstreamer1.0-plugins-codec2/1.0.0-r0/recipe-sysroot/usr/include/
QC2Client.h:9:10: fatal error: 'binder/IBinder.h' file not found

Change-Id: Id23c09331e25acc777bf7d9b779a62381a92caa4
Signed-off-by: Ferry Zhou <quic_tianguiz@quicinc.com>