meta-qti-bsp: fix build error due to incorrect md5sum of license
ERROR: python3-dockerpty-0.4.1-r0 do_populate_lic:xxxxxxxx [license-checksum]

Change-Id: I3e6abd511328adb6f683a47f7679d699299a226c